export const HEARING_SERVICES = [
  'None',
  'Hearing Assessment',
  'Pure Tone Audiometry',
  'Tympanometry',
  'BERA / ABR Testing',
  'OAE Testing',
  'Pediatric Hearing Assessment',
  'Hearing Aid Consultation',
  'Hearing Aid Trial',
  'Hearing Aid Fitting',
  'Hearing Aid Programming',
  'Hearing Aid Fine Tuning',
  'Digital Hearing Aid Sales',
  'Rechargeable Hearing Aids',
  'BTE Hearing Aids',
  'CIC / ITE Hearing Aids',
  'Hearing Aid Repair',
  'Hearing Aid Servicing',
  'Ear Mold / Ear Impression',
  'Hearing Aid Battery Supply',
] as const;

export const SPEECH_SERVICES = [
  'None',
  'Speech Assessment',
  'Language Assessment',
  'Speech Therapy for Children',
  'Speech Therapy for Adults',
  'Speech Therapy for Autism',
  'Speech Therapy for Delay in Speech',
  'Speech Therapy for Stammering / Stuttering',
  'Speech Therapy for Misarticulation',
  'Voice Therapy',
  'Oro-Motor Therapy',
  'Feeding / Swallowing Assessment',
  'Speech Therapy for Down Syndrome',
  'Speech Pathologist',
  'Special Education Support',
  'Parent Counseling for Speech Development',
  'Occupational Therapy Assessment',
  'Occupational Therapy for Children',
  'Sensory Integration Therapy',
  'Fine Motor Skill Training',
  'Hand Function Training',
  'ADL Training',
  'Occupational Therapy for Autism',
  'Occupational Therapy for Developmental Delay',
] as const;
